// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

namespace WebAPI.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("WebAPI.Entities.HotDogStand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.HasKey("Id");

                    b.ToTable("HotDogStands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("79865a99-7b94-4f85-8194-4ebf2d2bf48b"),
                            Address = "Strada Lalelelor"
                        },
                        new
                        {
                            Id = new Guid("004bac14-b91b-412e-aca6-96b37812ec80"),
                            Address = "Strada Malinilor"
                        },
                        new
                        {
                            Id = new Guid("a66f64e8-96af-4806-b458-22e9d382e458"),
                            Address = "Strada Copou"
                        },
                        new
                        {
                            Id = new Guid("de8b3f2e-5361-4a59-967c-7aac813939a1"),
                            Address = "Strada Stramosilor"
                        },
                        new
                        {
                            Id = new Guid("84a17198-7a72-4db1-b6a0-2fa1c5a0e7dc"),
                            Address = "Strada Brailei"
                        });
                });

            modelBuilder.Entity("WebAPI.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1051812-cc22-40a8-8bad-3230032e6fce"),
                            Category = "Sauce",
                            Description = "Ketchup for hot dogs",
                            Name = "Ketchup Tommy",
                            Price = 0f
                        },
                        new
                        {
                            Id = new Guid("d739001b-fe29-413c-8c11-3ed86c397dfd"),
                            Category = "Bread",
                            Description = "Bun for hot dog",
                            Name = "Happy Bunny",
                            Price = 0f
                        },
                        new
                        {
                            Id = new Guid("3fa1fb06-1c9a-4a43-b5aa-b6cadf528f6d"),
                            Category = "Meat",
                            Description = "Sausage for hot dogs",
                            Name = "Sausage",
                            Price = 0f
                        },
                        new
                        {
                            Id = new Guid("278aa4dc-a592-494e-b400-d67a2a6bdbd9"),
                            Category = "Sauce",
                            Description = "Mustard for hot dogs",
                            Name = "Golden Mustard",
                            Price = 0f
                        },
                        new
                        {
                            Id = new Guid("1f5df6eb-4d6a-4d17-8b71-80804c589406"),
                            Category = "Oils",
                            Description = "Oil for cooking",
                            Name = "Vinegar oil",
                            Price = 0f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
