// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.3.21201.2");

            modelBuilder.Entity("Domain.Entities.HotDogStand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("operator_id");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId")
                        .IsUnique();

                    b.ToTable("HotDogStands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14e8dabb-9ffe-4646-85ae-aed53a52b50c"),
                            Address = "Grimmer's Road",
                            OperatorId = new Guid("5e1115d2-f437-4f94-997b-2449cd849787")
                        },
                        new
                        {
                            Id = new Guid("af06b2ae-1a47-48c5-bbad-01dd9e78922a"),
                            Address = "Fieldfare Banks",
                            OperatorId = new Guid("81012b76-904b-4d96-bc95-3018cc0ba218")
                        },
                        new
                        {
                            Id = new Guid("aaeb4067-ca4e-4c3d-976c-e5f8e06ba28c"),
                            Address = "Imperial Passage",
                            OperatorId = new Guid("bcc2ae82-b3cc-445c-8644-9fdbfb107eac")
                        },
                        new
                        {
                            Id = new Guid("1d1baccd-d52b-4731-94f3-cde16c623e29"),
                            Address = "Woodville Square",
                            OperatorId = new Guid("fca8134c-74b8-4fd3-99ba-06a212ba1331")
                        });
                });

            modelBuilder.Entity("Domain.Entities.HotDogStandProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StandId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StandId");

                    b.ToTable("HotDogStandProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e757546a-f77f-44b9-aa6c-0ef6765aaf01"),
                            ProductId = new Guid("6b08b544-fb5c-40fd-bd73-2b8fee034c3e"),
                            Quantity = 7,
                            StandId = new Guid("14e8dabb-9ffe-4646-85ae-aed53a52b50c")
                        },
                        new
                        {
                            Id = new Guid("da53b52d-21cf-4d3d-b570-0c0d310e0734"),
                            ProductId = new Guid("4b27026c-98a1-4770-8de8-98a19150f3fd"),
                            Quantity = 10,
                            StandId = new Guid("14e8dabb-9ffe-4646-85ae-aed53a52b50c")
                        },
                        new
                        {
                            Id = new Guid("90feafa6-f623-4baa-be22-70b76744f9cd"),
                            ProductId = new Guid("cc9ee8b8-472c-4da0-b263-98003389051b"),
                            Quantity = 13,
                            StandId = new Guid("14e8dabb-9ffe-4646-85ae-aed53a52b50c")
                        },
                        new
                        {
                            Id = new Guid("b4705633-1d21-4219-8639-a6784b4c1599"),
                            ProductId = new Guid("6b08b544-fb5c-40fd-bd73-2b8fee034c3e"),
                            Quantity = 20,
                            StandId = new Guid("af06b2ae-1a47-48c5-bbad-01dd9e78922a")
                        },
                        new
                        {
                            Id = new Guid("8ce35291-004f-40f0-b81b-40e11af9c0d9"),
                            ProductId = new Guid("4b27026c-98a1-4770-8de8-98a19150f3fd"),
                            Quantity = 6,
                            StandId = new Guid("af06b2ae-1a47-48c5-bbad-01dd9e78922a")
                        });
                });

            modelBuilder.Entity("Domain.Entities.InventoryProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<uint>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryProducts");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("operator_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timesptamp");

                    b.Property<double>("Total")
                        .HasColumnType("REAL")
                        .HasColumnName("total");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.Entities.OrderProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrdersProducts");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b08b544-fb5c-40fd-bd73-2b8fee034c3e"),
                            Category = "HotDogs",
                            Description = "Basic hot dog with ketchup/mustard",
                            Name = "Hot Dog",
                            Price = 10f
                        },
                        new
                        {
                            Id = new Guid("4b27026c-98a1-4770-8de8-98a19150f3fd"),
                            Category = "HotDogs",
                            Description = "Hot dog with caramelized onions and ketchup",
                            Name = "Hot Onion Dog",
                            Price = 12.5f
                        },
                        new
                        {
                            Id = new Guid("cc9ee8b8-472c-4da0-b263-98003389051b"),
                            Category = "HotDogs",
                            Description = "Hot dog with melted gouda cheese and bacon",
                            Name = "Bacon Melt",
                            Price = 15f
                        },
                        new
                        {
                            Id = new Guid("b8956085-b852-40af-aeb7-9a39fa1c5cf9"),
                            Category = "Extras",
                            Description = "Regular fries",
                            Name = "Fries",
                            Price = 7.5f
                        },
                        new
                        {
                            Id = new Guid("f8f7461c-6f43-4c6a-bab3-716c448b7be6"),
                            Category = "Drinks",
                            Description = "Coke bottle",
                            Name = "Coke",
                            Price = 5f
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7edd790-fa67-4ec1-b07f-21a0e2108a67"),
                            Email = "customer@gmail.com",
                            Password = "B6C45863875E34487CA3C155ED145EFE12A74581E27BEFEC5AA661B8EE8CA6DD",
                            Role = 0,
                            Username = "customer"
                        },
                        new
                        {
                            Id = new Guid("36bb81cc-918c-4798-812f-88b32f496556"),
                            Email = "admin@gmail.com",
                            Password = "8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918",
                            Role = 3,
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("afa2ab34-cdfd-4aea-bb39-f6d19a6af456"),
                            Email = "supplier@gmail.com",
                            Password = "955ED10B73D6265B1ADCF768B94F8DD5D91F33309DB94B6B3AF4EFA822F1D9AF",
                            Role = 2,
                            Username = "supplier"
                        },
                        new
                        {
                            Id = new Guid("5e1115d2-f437-4f94-997b-2449cd849787"),
                            Email = "operator1@gmail.com",
                            Password = "941E65AF88E0945C9F7DB5C306B0EF0FC5763DF6BFC9D339FF235195885083A2",
                            Role = 1,
                            Username = "operator1"
                        },
                        new
                        {
                            Id = new Guid("81012b76-904b-4d96-bc95-3018cc0ba218"),
                            Email = "operator2@gmail.com",
                            Password = "6EED3508EEE654F48CC4D57910EAD9310E4B2B386248D56BD40BBF16FCD9A77F",
                            Role = 1,
                            Username = "operator2"
                        },
                        new
                        {
                            Id = new Guid("bcc2ae82-b3cc-445c-8644-9fdbfb107eac"),
                            Email = "operator3@gmail.com",
                            Password = "0A722A639AB7D77124CDD29A0AD96FF421D50DC97A079705C4D5B2D97CF347B0",
                            Role = 1,
                            Username = "operator3"
                        },
                        new
                        {
                            Id = new Guid("fca8134c-74b8-4fd3-99ba-06a212ba1331"),
                            Email = "operator4@gmail.com",
                            Password = "D71C5645CC3D232BCBD657888C4FF6AC0C6E33E2B89FB2162F8D96F276E8623A",
                            Role = 1,
                            Username = "operator4"
                        });
                });

            modelBuilder.Entity("Domain.Entities.HotDogStand", b =>
                {
                    b.HasOne("Domain.Entities.User", "Operator")
                        .WithOne("Stand")
                        .HasForeignKey("Domain.Entities.HotDogStand", "OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Domain.Entities.HotDogStandProduct", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.HotDogStand", "Stand")
                        .WithMany("StandProducts")
                        .HasForeignKey("StandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Stand");
                });

            modelBuilder.Entity("Domain.Entities.InventoryProduct", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.User", "Operator")
                        .WithMany("OperatorOrders")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("ClientOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.OrderProduct", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.HotDogStand", b =>
                {
                    b.Navigation("StandProducts");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("ClientOrders");

                    b.Navigation("OperatorOrders");

                    b.Navigation("Stand");
                });
#pragma warning restore 612, 618
        }
    }
}
